import sys
import os
import re
from typing import Dict, Any, Union

# Ensure root directory is on the path to resolve imports cleanly
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from modules.llm_service import GeminiClient
from src.prompts.templates import ASSIGNMENT_GENERATION_PROMPT
from src.config import get_settings
from src.utils.logger import get_logger

logger = get_logger(__name__)
settings = get_settings()

class AssignmentServiceError(Exception):
    """Custom exception raised for errors during assignment service operations."""
    pass

class AssignmentService:
    """Service to handle the creation and parsing of structured academic assignments using Gemini."""

    # Map page counts to word target descriptions
    LENGTH_MAP = {
        3: {"desc": "3 pages (Short Essay / Focus Analysis)", "words": 750},
        5: {"desc": "5 pages (Standard Research / Topic Exploration)", "words": 1250},
        10: {"desc": "10 pages (Comprehensive Term Paper / Extended Thesis)", "words": 2500}
    }

    def __init__(self, api_key: str = None) -> None:
        """
        Initialize AssignmentService.
        
        Args:
            api_key: Optional API key override. Defaults to value in settings.
        """
        self.api_key = api_key or settings.gemini_api_key
        if not self.api_key:
            logger.warning("AssignmentService initialized without a configured GEMINI_API_KEY.")

    def parse_markdown_sections(self, text: str) -> Dict[str, str]:
        """
        Parses structured assignment markdown text by headers.
        
        Args:
            text: Raw markdown text generated by the LLM.
            
        Returns:
            Dictionary mapped to structured keys: title, introduction, 
            main_content, conclusion, references.
        """
        sections = {
            "title": "",
            "introduction": "",
            "main_content": "",
            "conclusion": "",
            "references": ""
        }
        
        # Regex mappings to extract matching sections
        title_match = re.search(r"# ASSIGNMENT TITLE\s*(.*?)(?=# INTRODUCTION|$)", text, re.DOTALL | re.IGNORECASE)
        intro_match = re.search(r"# INTRODUCTION\s*(.*?)(?=# MAIN CONTENT|$)", text, re.DOTALL | re.IGNORECASE)
        main_match = re.search(r"# MAIN CONTENT\s*(.*?)(?=# CONCLUSION|$)", text, re.DOTALL | re.IGNORECASE)
        conclusion_match = re.search(r"# CONCLUSION\s*(.*?)(?=# REFERENCES|$)", text, re.DOTALL | re.IGNORECASE)
        refs_match = re.search(r"# REFERENCES\s*(.*?)(?=$)", text, re.DOTALL | re.IGNORECASE)
        
        if title_match:
            sections["title"] = title_match.group(1).strip()
        if intro_match:
            sections["introduction"] = intro_match.group(1).strip()
        if main_match:
            sections["main_content"] = main_match.group(1).strip()
        if conclusion_match:
            sections["conclusion"] = conclusion_match.group(1).strip()
        if refs_match:
            sections["references"] = refs_match.group(1).strip()
            
        return sections

    def generate_assignment(
        self, 
        pdf_text: str, 
        page_length: int = 3
    ) -> Dict[str, str]:
        """
        Generates a structured assignment of a specific page target from research text.
        
        Args:
            pdf_text: Cleaned text extracted from the PDF paper.
            page_length: Output size setting. Must be 3, 5, or 10 (default: 3).
            
        Returns:
            Dictionary with parsed assignment sections.
            
        Raises:
            AssignmentServiceError: If input parameters or API connections fail.
        """
        if not pdf_text or not pdf_text.strip():
            raise AssignmentServiceError("Cannot generate an assignment from empty text content.")
            
        if page_length not in self.LENGTH_MAP:
            raise AssignmentServiceError(
                f"Unsupported assignment page length: {page_length}. "
                f"Supported targets are: {list(self.LENGTH_MAP.keys())}"
            )
            
        if not self.api_key:
            raise AssignmentServiceError("GEMINI_API_KEY must be configured to use AssignmentService.")

        target = self.LENGTH_MAP[page_length]
        logger.info(
            f"Generating assignment (length={page_length} pages, word_target={target['words']}) "
            f"for text content (length={len(pdf_text)})."
        )
        
        try:
            # Reusable Gemini client
            client = GeminiClient(
                api_key=self.api_key,
                model_name=settings.gemini_model,
                temperature=0.5  # Slightly creative but focused
            )
            
            # Execute prompt template
            raw_response = client.execute_prompt(
                prompt_template=ASSIGNMENT_GENERATION_PROMPT,
                input_variables={
                    "text": pdf_text,
                    "length_desc": target["desc"],
                    "word_count": str(target["words"])
                }
            )
            
            logger.info("Assignment prompt execution completed. Parsing output sections.")
            return self.parse_markdown_sections(raw_response)
            
        except Exception as e:
            logger.error(f"Assignment generation service failed: {str(e)}", exc_info=True)
            raise AssignmentServiceError(f"Error executing assignment generator service: {str(e)}") from e
