import sys
import os
import re
from typing import Dict, Any, Union

# Ensure root directory is on the path to resolve imports cleanly
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from modules.llm_service import GeminiClient
from src.prompts.templates import STUDY_NOTES_PROMPT
from src.config import get_settings
from src.utils.logger import get_logger

logger = get_logger(__name__)
settings = get_settings()

class NotesServiceError(Exception):
    """Custom exception raised for errors during study notes service execution."""
    pass

class NotesService:
    """Service to handle structured academic study notes generation using Gemini."""

    def __init__(self, api_key: str = None) -> None:
        """
        Initialize NotesService.
        
        Args:
            api_key: Optional API key override. Defaults to value in settings.
        """
        self.api_key = api_key or settings.gemini_api_key
        if not self.api_key:
            logger.warning("NotesService initialized without a configured GEMINI_API_KEY.")

    def parse_markdown_sections(self, text: str) -> Dict[str, str]:
        """
        Parses the study notes markdown text by headings.
        
        Args:
            text: Raw markdown text generated by the LLM.
            
        Returns:
            Dictionary mapped to structured keys: chapter_notes, key_concepts, 
            revision_points, exam_tips.
        """
        sections = {
            "chapter_notes": "",
            "key_concepts": "",
            "revision_points": "",
            "exam_tips": ""
        }
        
        # Regex groupings to extract content between headers
        chapter_match = re.search(r"# CHAPTER-WISE NOTES\s*(.*?)(?=# KEY CONCEPTS|$)", text, re.DOTALL | re.IGNORECASE)
        concepts_match = re.search(r"# KEY CONCEPTS\s*(.*?)(?=# REVISION POINTS|$)", text, re.DOTALL | re.IGNORECASE)
        revision_match = re.search(r"# REVISION POINTS\s*(.*?)(?=# EXAM TIPS|$)", text, re.DOTALL | re.IGNORECASE)
        tips_match = re.search(r"# EXAM TIPS\s*(.*?)(?=$)", text, re.DOTALL | re.IGNORECASE)
        
        if chapter_match:
            sections["chapter_notes"] = chapter_match.group(1).strip()
        if concepts_match:
            sections["key_concepts"] = concepts_match.group(1).strip()
        if revision_match:
            sections["revision_points"] = revision_match.group(1).strip()
        if tips_match:
            sections["exam_tips"] = tips_match.group(1).strip()
            
        return sections

    def generate_notes(self, pdf_text: str) -> Dict[str, str]:
        """
        Generates structured study notes from academic PDF text using Gemini.
        
        Args:
            pdf_text: Raw or clean text of the research publication.
            
        Returns:
            Dictionary with parsed study notes elements.
            
        Raises:
            NotesServiceError: If input text is empty or API call fails.
        """
        if not pdf_text or not pdf_text.strip():
            raise NotesServiceError("Cannot generate notes from empty text content.")
            
        if not self.api_key:
            raise NotesServiceError("GEMINI_API_KEY must be configured to use NotesService.")

        logger.info(f"Generating academic study notes for text content (length={len(pdf_text)}).")
        try:
            # Reusable Gemini client
            client = GeminiClient(
                api_key=self.api_key,
                model_name=settings.gemini_model,
                temperature=0.3  # Structured and academic
            )
            
            # Execute prompt template
            raw_response = client.execute_prompt(
                prompt_template=STUDY_NOTES_PROMPT,
                input_variables={"text": pdf_text}
            )
            
            logger.info("Study notes prompt execution completed. Parsing output sections.")
            return self.parse_markdown_sections(raw_response)
            
        except Exception as e:
            logger.error(f"Notes service failed: {str(e)}", exc_info=True)
            raise NotesServiceError(f"Error executing notes service pipeline: {str(e)}") from e
