import sys
import os
import re
from typing import Dict, Any, Union

# Ensure root directory is on the path to resolve imports cleanly
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from modules.llm_service import GeminiClient
from src.prompts.templates import ACADEMIC_SUMMARY_PROMPT
from src.config import get_settings
from src.utils.logger import get_logger

logger = get_logger(__name__)
settings = get_settings()

class SummaryServiceError(Exception):
    """Custom exception raised for errors during summary service execution."""
    pass

class SummaryService:
    """Service to handle structured academic summarization operations using Gemini."""

    def __init__(self, api_key: str = None) -> None:
        """
        Initialize SummaryService.
        
        Args:
            api_key: Optional API key override. Defaults to value in settings.
        """
        self.api_key = api_key or settings.gemini_api_key
        if not self.api_key:
            logger.warning("SummaryService initialized without a configured GEMINI_API_KEY.")

    def parse_markdown_sections(self, text: str) -> Dict[str, str]:
        """
        Helper method to parse the structured Gemini output sections by markdown headers.
        
        Args:
            text: Raw markdown text generated by the LLM.
            
        Returns:
            Dictionary mapped to structured keys: executive_summary, key_topics, 
            important_concepts, important_definitions.
        """
        sections = {
            "executive_summary": "",
            "key_topics": "",
            "important_concepts": "",
            "important_definitions": ""
        }
        
        # Regex groupings to extract content between headers
        exec_match = re.search(r"# EXECUTIVE SUMMARY\s*(.*?)(?=# KEY TOPICS|$)", text, re.DOTALL | re.IGNORECASE)
        topics_match = re.search(r"# KEY TOPICS\s*(.*?)(?=# IMPORTANT CONCEPTS|$)", text, re.DOTALL | re.IGNORECASE)
        concepts_match = re.search(r"# IMPORTANT CONCEPTS\s*(.*?)(?=# IMPORTANT DEFINITIONS|$)", text, re.DOTALL | re.IGNORECASE)
        defs_match = re.search(r"# IMPORTANT DEFINITIONS\s*(.*?)(?=$)", text, re.DOTALL | re.IGNORECASE)
        
        if exec_match:
            sections["executive_summary"] = exec_match.group(1).strip()
        if topics_match:
            sections["key_topics"] = topics_match.group(1).strip()
        if concepts_match:
            sections["important_concepts"] = concepts_match.group(1).strip()
        if defs_match:
            sections["important_definitions"] = defs_match.group(1).strip()
            
        return sections

    def summarize_pdf_content(self, pdf_text: str) -> Dict[str, str]:
        """
        Generates a structured summary of academic PDF text using Gemini.
        
        Args:
            pdf_text: Raw or clean text of the research publication.
            
        Returns:
            Dictionary with parsed summary elements.
            
        Raises:
            SummaryServiceError: If input text is invalid or API execution fails.
        """
        if not pdf_text or not pdf_text.strip():
            raise SummaryServiceError("Cannot generate summary from empty text content.")
            
        if not self.api_key:
            raise SummaryServiceError("GEMINI_API_KEY must be configured to use SummaryService.")

        logger.info(f"Generating academic summary for text content (length={len(pdf_text)}).")
        try:
            # Reusable Gemini client
            client = GeminiClient(
                api_key=self.api_key,
                model_name=settings.gemini_model,
                temperature=0.2  # Keep summary deterministic
            )
            
            # Execute prompt template
            raw_response = client.execute_prompt(
                prompt_template=ACADEMIC_SUMMARY_PROMPT,
                input_variables={"text": pdf_text}
            )
            
            logger.info("Summary prompt execution completed. Parsing output sections.")
            return self.parse_markdown_sections(raw_response)
            
        except Exception as e:
            logger.error(f"Summarization service failed: {str(e)}", exc_info=True)
            raise SummaryServiceError(f"Error executing summary service pipeline: {str(e)}") from e
