import sys
import os
import re
from typing import Dict, Any, Union

# Ensure root directory is on the path to resolve imports cleanly
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from modules.llm_service import GeminiClient
from src.prompts.templates import VIVA_QUESTIONS_PROMPT
from src.config import get_settings
from src.utils.logger import get_logger

logger = get_logger(__name__)
settings = get_settings()

class VivaServiceError(Exception):
    """Custom exception raised for errors during viva question service operations."""
    pass

class VivaService:
    """Service to handle the creation and parsing of structured academic viva questions using Gemini."""

    def __init__(self, api_key: str = None) -> None:
        """
        Initialize VivaService.
        
        Args:
            api_key: Optional API key override. Defaults to value in settings.
        """
        self.api_key = api_key or settings.gemini_api_key
        if not self.api_key:
            logger.warning("VivaService initialized without a configured GEMINI_API_KEY.")

    def parse_markdown_sections(self, text: str) -> Dict[str, str]:
        """
        Parses structured viva questions markdown text by difficulty headers.
        
        Args:
            text: Raw markdown text generated by the LLM.
            
        Returns:
            Dictionary mapped to structured keys: beginner, intermediate, advanced.
        """
        sections = {
            "beginner": "",
            "intermediate": "",
            "advanced": ""
        }
        
        # Regex mappings to extract matching sections
        beg_match = re.search(r"# BEGINNER QUESTIONS\s*(.*?)(?=# INTERMEDIATE QUESTIONS|$)", text, re.DOTALL | re.IGNORECASE)
        int_match = re.search(r"# INTERMEDIATE QUESTIONS\s*(.*?)(?=# ADVANCED QUESTIONS|$)", text, re.DOTALL | re.IGNORECASE)
        adv_match = re.search(r"# ADVANCED QUESTIONS\s*(.*?)(?=$)", text, re.DOTALL | re.IGNORECASE)
        
        if beg_match:
            sections["beginner"] = beg_match.group(1).strip()
        if int_match:
            sections["intermediate"] = int_match.group(1).strip()
        if adv_match:
            sections["advanced"] = adv_match.group(1).strip()
            
        return sections

    def generate_viva_questions(self, pdf_text: str) -> Dict[str, str]:
        """
        Generates structured viva questions (20 per level) from research text.
        
        Args:
            pdf_text: Cleaned text extracted from the PDF paper.
            
        Returns:
            Dictionary with parsed viva question lists.
            
        Raises:
            VivaServiceError: If input text is empty or API execution fails.
        """
        if not pdf_text or not pdf_text.strip():
            raise VivaServiceError("Cannot generate viva questions from empty text content.")
            
        if not self.api_key:
            raise VivaServiceError("GEMINI_API_KEY must be configured to use VivaService.")

        logger.info(f"Generating academic viva questions for text content (length={len(pdf_text)}).")
        try:
            # Reusable Gemini client
            client = GeminiClient(
                api_key=self.api_key,
                model_name=settings.gemini_model,
                temperature=0.4  # Balanced focus and variance
            )
            
            # Execute prompt template
            raw_response = client.execute_prompt(
                prompt_template=VIVA_QUESTIONS_PROMPT,
                input_variables={"text": pdf_text}
            )
            
            logger.info("Viva questions prompt execution completed. Parsing output sections.")
            return self.parse_markdown_sections(raw_response)
            
        except Exception as e:
            logger.error(f"Viva question service failed: {str(e)}", exc_info=True)
            raise VivaServiceError(f"Error executing viva question generator service: {str(e)}") from e
